#!/usr/bin/env python3
"""
Export ONNX model weights to pure-C header with float32 dequantization.

Usage:
  python3 export_weights.py [output_dir]

Output:
  include/model_weights.h  — all weights dequantized to float32 C arrays
  include/model_meta.h     — architecture constants (shapes, layer params)
  include/gelu_consts.h    — GELU constants extracted from ONNX Constant nodes
"""

import onnx
import numpy as np
import sys, os

MODEL_PATH = "/home/legion/Downloads/battery_cnn_int8.onnx"
OUT_DIR = sys.argv[1] if len(sys.argv) > 1 else "/home/legion/yg2lx-work/cnn_inference/include"


def dtype_str(elem_type):
    return {1: "float", 2: "uint8", 3: "int8", 6: "int32", 7: "int64"}.get(elem_type, f"type_{elem_type}")


def sanitize(name):
    """Make a valid C identifier from an ONNX tensor name."""
    return name.replace("/", "_").replace(".", "_").replace(":", "_").replace("-", "_")


def write_weights(model, out_dir):
    """Extract weights, dequantize INT8→float32, write C header."""
    graph = model.graph

    # Build dict: initializer name → numpy array
    init = {}
    for w in graph.initializer:
        init[w.name] = onnx.numpy_helper.to_array(w)

    # Build dict: quantized_weight → (scale_name, zero_point_name)
    quant_map = {}  # weight_quantized_name → (scale_name, zp_name, float_name)
    for w in graph.initializer:
        name = w.name
        if name.endswith("_quantized"):
            base = name[:-len("_quantized")]
            scale_name = base + "_scale"
            zp_name = base + "_zero_point"
            float_name = base.replace("_quantized", "")  # e.g. onnx::Conv_190
            quant_map[name] = (scale_name, zp_name, float_name)

    lines = []
    lines.append("/* Auto-generated by export_weights.py — DO NOT EDIT */")
    lines.append(f"/* Model: battery_cnn_int8.onnx */")
    total_p = sum(onnx.numpy_helper.to_array(w).size for w in graph.initializer)
    lines.append(f"/* Total parameters: {total_p:,} */")
    lines.append("")
    lines.append("#ifndef MODEL_WEIGHTS_H")
    lines.append("#define MODEL_WEIGHTS_H")
    lines.append("")
    lines.append('#include <stddef.h>')
    lines.append("")

    # Process all initializers
    for w in sorted(graph.initializer, key=lambda x: x.name):
        name = w.name
        arr = onnx.numpy_helper.to_array(w)
        c_name = sanitize(name)

        # Skip reshape_shape tensors (not needed for inference)
        if "reshape_shape" in name:
            continue
        # Skip scale and zero_point — we dequantize at export time
        if name.endswith("_scale") or name.endswith("_zero_point"):
            continue

        # For quantized weights, dequantize
        if name.endswith("_quantized"):
            scale_name, zp_name, _ = quant_map[name]
            if scale_name in init and zp_name in init:
                scale = init[scale_name].item()
                zp = init[zp_name].item()
                arr_f32 = (arr.astype(np.float32) - zp) * scale
                arr = arr_f32.astype(np.float32)
                c_name = sanitize(name.replace("_quantized", ""))  # clean name
                comment = f"  /* [{(' × '.join(str(d) for d in arr_f32.shape))}] float32 (dequantized from int8, scale={scale:.8f}, zp={zp}) */"
            else:
                comment = f"  /* [{(' × '.join(str(d) for d in arr.shape))}] {dtype_str(w.data_type)} */"
        else:
            comment = f"  /* [{(' × '.join(str(d) for d in arr.shape))}] {dtype_str(w.data_type)} */"

        # Flatten to 1D C array
        flat = arr.flatten()
        lines.append(f"// {comment.strip()}")
        lines.append(f"static const float {c_name}[{len(flat)}] = {{")

        # Pretty-print: 8 values per line
        for i in range(0, len(flat), 8):
            chunk = flat[i:i+8]
            vals = ", ".join(f"{v:.8f}f" if abs(v) >= 1e-10 else f"{v:.10e}f" for v in chunk)
            comma = "," if i + 8 < len(flat) else ""
            lines.append(f"    {vals}{comma}")

        lines.append("};")
        lines.append("")

    lines.append("#endif /* MODEL_WEIGHTS_H */")
    lines.append("")

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "model_weights.h")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote: {path}  ({len(lines)} lines)")


def write_meta(model, out_dir):
    """Write architecture constants: shapes, layer params."""
    graph = model.graph
    lines = []
    lines.append("/* Auto-generated by export_weights.py */")
    lines.append("#ifndef MODEL_META_H")
    lines.append("#define MODEL_META_H")
    lines.append("")
    lines.append("/* ── Input / Output ── */")
    lines.append("#define MODEL_INPUT_CHANNELS   2")
    lines.append("#define MODEL_INPUT_LENGTH      128")
    lines.append("#define MODEL_NUM_CLASSES       3       /* stage_logits */")
    lines.append("")

    lines.append("/* ── Stem ── */")
    lines.append("#define STEM_CONV_IN_CH          2")
    lines.append("#define STEM_CONV_OUT_CH         16")
    lines.append("#define STEM_CONV_KERNEL         7")
    lines.append("#define STEM_CONV_STRIDE         2")
    lines.append("#define STEM_CONV_PAD            3")
    lines.append("#define STEM_OUT_LENGTH          64      /* (128 - 7 + 2*3)/2 + 1 = 64 */")
    lines.append("")

    lines.append("/* ── Body Block 0 (16ch → 16ch, identity skip, then pool) ── */")
    lines.append("#define B0_CONV1_IN_CH           16")
    lines.append("#define B0_CONV1_OUT_CH          16")
    lines.append("#define B0_CONV1_KERNEL          7")
    lines.append("#define B0_CONV1_STRIDE          1")
    lines.append("#define B0_CONV1_PAD             3")
    lines.append("#define B0_CONV1_OUT_LEN         64      /* (64-7+6)/1+1 = 64 */")
    lines.append("")
    lines.append("#define B0_CONV2_IN_CH           16")
    lines.append("#define B0_CONV2_OUT_CH          16")
    lines.append("#define B0_CONV2_KERNEL          7")
    lines.append("#define B0_CONV2_STRIDE          1")
    lines.append("#define B0_CONV2_PAD             3")
    lines.append("#define B0_CONV2_OUT_LEN         64")
    lines.append("")
    lines.append("#define B0_POOL_KERNEL           2")
    lines.append("#define B0_POOL_STRIDE           2")
    lines.append("#define B0_OUT_LENGTH            32      /* 64/2 = 32 */")
    lines.append("")

    lines.append("/* ── Body Block 1 (16ch → 32ch, 1×1 shortcut, then pool) ── */")
    lines.append("#define B1_SC_IN_CH              16")
    lines.append("#define B1_SC_OUT_CH             32")
    lines.append("#define B1_SC_KERNEL             1")
    lines.append("#define B1_SC_STRIDE             1")
    lines.append("#define B1_SC_PAD                0")
    lines.append("#define B1_CONV1_IN_CH           16")
    lines.append("#define B1_CONV1_OUT_CH          32")
    lines.append("#define B1_CONV1_KERNEL          7")
    lines.append("#define B1_CONV1_STRIDE          1")
    lines.append("#define B1_CONV1_PAD             3")
    lines.append("#define B1_CONV1_OUT_LEN         32")
    lines.append("#define B1_CONV2_IN_CH           32")
    lines.append("#define B1_CONV2_OUT_CH          32")
    lines.append("#define B1_CONV2_KERNEL          7")
    lines.append("#define B1_CONV2_STRIDE          1")
    lines.append("#define B1_CONV2_PAD             3")
    lines.append("#define B1_CONV2_OUT_LEN         32")
    lines.append("#define B1_POOL_KERNEL           2")
    lines.append("#define B1_POOL_STRIDE           2")
    lines.append("#define B1_OUT_LENGTH            16      /* 32/2 = 16 */")
    lines.append("")

    lines.append("/* ── Body Block 2 (32ch → 48ch, 1×1 shortcut, then pool) ── */")
    lines.append("#define B2_SC_IN_CH              32")
    lines.append("#define B2_SC_OUT_CH             48")
    lines.append("#define B2_SC_KERNEL             1")
    lines.append("#define B2_SC_STRIDE             1")
    lines.append("#define B2_SC_PAD                0")
    lines.append("#define B2_CONV1_IN_CH           32")
    lines.append("#define B2_CONV1_OUT_CH          48")
    lines.append("#define B2_CONV1_KERNEL          5")
    lines.append("#define B2_CONV1_STRIDE          1")
    lines.append("#define B2_CONV1_PAD             2")
    lines.append("#define B2_CONV1_OUT_LEN         16")
    lines.append("#define B2_CONV2_IN_CH           48")
    lines.append("#define B2_CONV2_OUT_CH          48")
    lines.append("#define B2_CONV2_KERNEL          5")
    lines.append("#define B2_CONV2_STRIDE          1")
    lines.append("#define B2_CONV2_PAD             2")
    lines.append("#define B2_CONV2_OUT_LEN         16")
    lines.append("#define B2_POOL_KERNEL           2")
    lines.append("#define B2_POOL_STRIDE           2")
    lines.append("#define B2_OUT_LENGTH            8       /* 16/2 = 8 */")
    lines.append("")

    lines.append("/* ── Feature dimension (after GAP) ── */")
    lines.append("#define FEATURE_DIM               48")
    lines.append("")

    lines.append("/* ── Classification Head ── */")
    lines.append("#define CLS_FC1_IN                48")
    lines.append("#define CLS_FC1_OUT               48")
    lines.append("#define CLS_FC2_IN                48")
    lines.append("#define CLS_FC2_OUT               24")
    lines.append("#define CLS_FC3_IN                24")
    lines.append("#define CLS_FC3_OUT               3")
    lines.append("")

    lines.append("/* ── RUL Regression Head ── */")
    lines.append("#define RUL_FC1_IN                48")
    lines.append("#define RUL_FC1_OUT               48")
    lines.append("#define RUL_FC2_IN                48")
    lines.append("#define RUL_FC2_OUT               24")
    lines.append("#define RUL_FC3_IN                24")
    lines.append("#define RUL_FC3_OUT               1")
    lines.append("")

    lines.append("/* ── Buffer sizing ── */")
    lines.append("/* Max intermediate buffer size across all layers */")
    max_buf = max(
        1 * 16 * 64,   # stem out
        1 * 16 * 64,   # b0 conv1 out
        1 * 16 * 64,   # b0 conv2 out
        1 * 16 * 32,   # b0 pool out
        1 * 32 * 32,   # b1 conv1/sc out
        1 * 32 * 32,   # b1 conv2 out
        1 * 32 * 16,   # b1 pool out
        1 * 48 * 16,   # b2 conv1/sc out
        1 * 48 * 16,   # b2 conv2 out
        1 * 48 * 8,    # b2 pool out
        48,            # features
        48, 24, 3,     # cls
        48, 24, 1,     # rul
    )
    lines.append(f"#define MAX_BUF_SIZE              {max_buf}")
    lines.append("")

    lines.append("#endif /* MODEL_META_H */")

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "model_meta.h")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote: {path}  ({len(lines)} lines)")


def write_gelu_consts(model, out_dir):
    """Extract GELU constants (sqrt(2), 1.0, 0.5) from Constant nodes."""
    graph = model.graph

    # Find constant nodes and their outputs
    const_map = {}
    for node in graph.node:
        if node.op_type == "Constant":
            for a in node.attribute:
                if a.name == "value":
                    val = onnx.numpy_helper.to_array(a.t)
                    const_map[node.output[0]] = val

    lines = []
    lines.append("/* Auto-generated GELU constants from ONNX model */")
    lines.append("#ifndef GELU_CONSTS_H")
    lines.append("#define GELU_CONSTS_H")
    lines.append("")

    # Collect unique GELU blocks and their constants
    # Pattern: {divisor, adder, multiplier} from each activation block
    gelu_blocks = {}
    for i, node in enumerate(graph.node):
        if node.op_type == "Div" and "act" in node.input[1] or \
           node.op_type == "Div" and "stem" in node.input[1]:
            div_by = node.input[1]
            if div_by in const_map:
                val = const_map[div_by].item()
                lines.append(f"// GELU sqrt(2) divisor from {div_by}")
                lines.append(f"#define GELU_SQRT2  {val:.8f}f")
                break

    # General case: write all constants for reference
    lines.append("")
    lines.append("/* All GELU parameters (extracted from model, should be identical across blocks) */")

    seen_vals = set()
    for name, val in sorted(const_map.items()):
        if val.size == 1:
            v = val.item()
            c_name = sanitize(name)
            # Only show unique values
            if v not in seen_vals:
                seen_vals.add(v)
                lines.append(f"// {name}")
                lines.append(f"#define {c_name}  {v:.8f}f")
                lines.append("")

    lines.append("#endif /* GELU_CONSTS_H */")

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "gelu_consts.h")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote: {path}  ({len(lines)} lines)")


def main():
    print("Loading model...")
    model = onnx.load(MODEL_PATH)
    print(f"  IR v{model.ir_version}, opset {model.opset_import[0].version}")
    print()

    write_weights(model, OUT_DIR)
    write_meta(model, OUT_DIR)
    write_gelu_consts(model, OUT_DIR)

    print()
    print("Done. Ready for C compilation.")

if __name__ == "__main__":
    main()
