/* Auto-generated by export_weights.py */
#ifndef CNN_META_H
#define CNN_META_H

/* ── Input / Output ── */
#define CNN_INPUT_CHANNELS          2
#define CNN_INPUT_LENGTH            128
#define CNN_NUM_CLASSES             3

/* ── Stem: Conv1d(2→16, k7, s2, p3) ── */
#define CNN_STEM_IN_CH              2
#define CNN_STEM_OUT_CH             16
#define CNN_STEM_KERNEL             7
#define CNN_STEM_STRIDE             2
#define CNN_STEM_PAD                3
#define CNN_STEM_OUT_LEN            64

/* ── Body Block 0: 16→16, identity skip, k7 ── */
#define CNN_B0_CONV1_IN_CH          16
#define CNN_B0_CONV1_OUT_CH         16
#define CNN_B0_CONV1_KERNEL         7
#define CNN_B0_CONV1_PAD            3
#define CNN_B0_CONV2_IN_CH          16
#define CNN_B0_CONV2_OUT_CH         16
#define CNN_B0_CONV2_KERNEL         7
#define CNN_B0_CONV2_PAD            3
#define CNN_B0_CONV2_OUT_LEN        64
#define CNN_B0_POOL_KERNEL          2
#define CNN_B0_POOL_STRIDE          2
#define CNN_B0_OUT_LEN              32

/* ── Body Block 1: 16→32, 1×1 shortcut, k7 ── */
#define CNN_B1_SC_IN_CH             16
#define CNN_B1_SC_OUT_CH            32
#define CNN_B1_CONV1_IN_CH          16
#define CNN_B1_CONV1_OUT_CH         32
#define CNN_B1_CONV1_KERNEL         7
#define CNN_B1_CONV1_PAD            3
#define CNN_B1_CONV1_OUT_LEN        32
#define CNN_B1_CONV2_IN_CH          32
#define CNN_B1_CONV2_OUT_CH         32
#define CNN_B1_CONV2_KERNEL         7
#define CNN_B1_CONV2_PAD            3
#define CNN_B1_CONV2_OUT_LEN        32
#define CNN_B1_POOL_KERNEL          2
#define CNN_B1_POOL_STRIDE          2
#define CNN_B1_OUT_LEN              16

/* ── Body Block 2: 32→48, 1×1 shortcut, k5 ── */
#define CNN_B2_SC_IN_CH             32
#define CNN_B2_SC_OUT_CH            48
#define CNN_B2_CONV1_IN_CH          32
#define CNN_B2_CONV1_OUT_CH         48
#define CNN_B2_CONV1_KERNEL         5
#define CNN_B2_CONV1_PAD            2
#define CNN_B2_CONV1_OUT_LEN        16
#define CNN_B2_CONV2_IN_CH          48
#define CNN_B2_CONV2_OUT_CH         48
#define CNN_B2_CONV2_KERNEL         5
#define CNN_B2_CONV2_PAD            2
#define CNN_B2_CONV2_OUT_LEN        16
#define CNN_B2_POOL_KERNEL          2
#define CNN_B2_POOL_STRIDE          2
#define CNN_B2_OUT_LEN              8

/* ── GAP + Heads ── */
#define CNN_FEATURE_DIM             48
#define CNN_CLS_FC1_IN              48
#define CNN_CLS_FC1_OUT             48
#define CNN_CLS_FC2_IN              48
#define CNN_CLS_FC2_OUT             24
#define CNN_CLS_FC3_IN              24
#define CNN_CLS_FC3_OUT             3
#define CNN_RUL_FC1_IN              48
#define CNN_RUL_FC1_OUT             48
#define CNN_RUL_FC2_IN              48
#define CNN_RUL_FC2_OUT             24
#define CNN_RUL_FC3_IN              24
#define CNN_RUL_FC3_OUT             1

/* ── Buffer sizing ── */
#define CNN_MAX_BUF_SIZE            1024

#endif /* CNN_META_H */