/* Auto-generated by export_weights.py */
#ifndef PINN_META_H
#define PINN_META_H

/* ── Input / Output ── */
#define PINN_INPUT_DIM            132
#define PINN_OUTPUT_DIM            1

/* ── Encoder ── */
#define ENC_FC1_IN                 132
#define ENC_FC1_OUT                128
#define ENC_NORM1_DIM              128

#define ENC_FC2_IN                 128
#define ENC_FC2_OUT                128
#define ENC_NORM2_DIM              128

#define ENC_FC3_IN                 128
#define ENC_FC3_OUT                64

/* ── Residual Block ── */
#define RES_FC1_IN                 64
#define RES_FC1_OUT                64
#define RES_NORM1_DIM              64
#define RES_FC2_IN                 64
#define RES_FC2_OUT                64
#define RES_NORM2_DIM              64

/* ── Head ── */
#define HEAD_FC1_IN                64
#define HEAD_FC1_OUT               32
#define HEAD_NORM_DIM              32
#define HEAD_FC2_IN                32
#define HEAD_FC2_OUT               1

/* ── Aux resistance head ── */
#define AUX_RES_IN                 64
#define AUX_RES_OUT                1

/* ── Activation ── */
#define PINN_ACTIVATION            "gelu"

/* ── LayerNorm epsilon ── */
#define LAYERNORM_EPS              1e-5f

/* ── Buffer sizing ── */
#define PINN_MAX_BUF_SIZE           132

#endif /* PINN_META_H */