#!/usr/bin/env python3
"""
Export BOTH PINN and CNN ONNX FP32 model weights → pure-C float32 headers.

Transposes Gemm weights from ONNX [out,in] layout to C-friendly [in,out] layout.

Usage:
  python3 export_weights.py

Output:
  include/pinn_weights.h   — PINN  weights as float32 C arrays
  include/pinn_meta.h      — PINN  architecture constants
  include/cnn_weights.h    — CNN   weights as float32 C arrays
  include/cnn_meta.h       — CNN   architecture constants
  include/scalers.h        — StandardScaler mean/std parameters
"""

import onnx
import numpy as np
import pickle
import os, sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "include")

PINN_ONNX = "/home/legion/PINN_CNN/pinn/checkpoints/battery_pinn_fp32.onnx"
CNN_ONNX  = "/home/legion/PINN_CNN/cnn/checkpoints/battery_cnn_fp32.onnx"
PINN_SCALER = "/home/legion/PINN_CNN/pinn/checkpoints/feature_scaler.pkl"
CNN_SCALER  = "/home/legion/PINN_CNN/cnn/checkpoints/ic_scaler.pkl"


def sanitize(name):
    return name.replace("/", "_").replace(".", "_").replace(":", "_").replace("-", "_")


# ═══════════════════════════════════════════════════════════════════════
# FP32 weight extractor for ONNX models
# ═══════════════════════════════════════════════════════════════════════

def extract_weights_fp32(model_path):
    """Return dict: c_var_name → (float32_array, comment_str) for all weights.

    Handles:
      - Gemm weights with transB=1: transpose from [out,in] to [in,out]
      - Conv weights: keep [out_ch, in_ch, kernel] layout (matches C conv1d)
      - Biases and 1D params: keep as-is
    """
    model = onnx.load(model_path)
    graph = model.graph

    # Build initializer dict
    init_map = {}
    for w in graph.initializer:
        init_map[w.name] = onnx.numpy_helper.to_array(w)

    # Build map: initializer name → whether to transpose (for Gemm with transB=1)
    transpose_set = set()
    for node in graph.node:
        if node.op_type == "Gemm":
            transB = False
            for attr in node.attribute:
                if attr.name == "transB" and attr.i == 1:
                    transB = True
            if transB and len(node.input) >= 2:
                w_name = node.input[1]   # weight is 2nd input of Gemm
                if w_name in init_map:
                    transpose_set.add(w_name)

    weights = {}

    for w in graph.initializer:
        name = w.name
        arr = onnx.numpy_helper.to_array(w)
        c_name = sanitize(name)

        # Skip reshape_shape tensors
        if "reshape_shape" in name:
            continue

        dtype = {1: "float32", 2: "uint8", 3: "int8", 6: "int32", 7: "int64"}.get(
            w.data_type, f"type_{w.data_type}")

        shape_str = " × ".join(str(d) for d in arr.shape)

        if name in transpose_set:
            # Gemm weight: ONNX stores [out,in], C expects [in,out]
            arr = arr.T.copy()
            comment = f"/* [{shape_str}] → transposed to [{(' × '.join(str(d) for d in arr.shape))}] {dtype} */"
        else:
            comment = f"/* [{shape_str}] {dtype} */"

        flat = arr.astype(np.float32).flatten()
        weights[c_name] = (flat, comment)

    return weights


def write_weight_header(weights, guard_name, out_path):
    """Write a C header file from extracted weights."""
    lines = []
    lines.append("/* Auto-generated by export_weights.py — DO NOT EDIT */")
    lines.append(f"/* Total arrays: {len(weights)} */")
    lines.append("")
    lines.append(f"#ifndef {guard_name}")
    lines.append(f"#define {guard_name}")
    lines.append("")
    lines.append('#include <stddef.h>')
    lines.append("")

    for c_name, (arr, comment) in sorted(weights.items()):
        lines.append(f"// {comment.strip()}")
        lines.append(f"static const float {c_name}[{len(arr)}] = {{")

        for i in range(0, len(arr), 8):
            chunk = arr[i:i+8]
            vals = ", ".join(
                f"{v:.8f}f" if abs(v) >= 1e-10 and abs(v) < 1e6
                else f"{v:.10e}f"
                for v in chunk
            )
            comma = "," if i + 8 < len(arr) else ""
            lines.append(f"    {vals}{comma}")

        lines.append("};")
        lines.append("")

    lines.append(f"#endif /* {guard_name} */")
    lines.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    total_floats = sum(len(arr) for arr, _ in weights.values())
    print(f"  Wrote: {out_path}  ({len(lines)} lines, {total_floats:,} float32 values, ~{total_floats*4/1024:.1f} KB)")


# ═══════════════════════════════════════════════════════════════════════
# PINN meta
# ═══════════════════════════════════════════════════════════════════════

def write_pinn_meta(out_dir):
    lines = []
    lines.append("/* Auto-generated by export_weights.py */")
    lines.append("#ifndef PINN_META_H")
    lines.append("#define PINN_META_H")
    lines.append("")
    lines.append("/* ── Input / Output ── */")
    lines.append("#define PINN_INPUT_DIM            132")
    lines.append("#define PINN_OUTPUT_DIM            1")
    lines.append("")
    lines.append("/* ── Encoder ── */")
    lines.append("#define ENC_FC1_IN                 132")
    lines.append("#define ENC_FC1_OUT                128")
    lines.append("#define ENC_NORM1_DIM              128")
    lines.append("")
    lines.append("#define ENC_FC2_IN                 128")
    lines.append("#define ENC_FC2_OUT                128")
    lines.append("#define ENC_NORM2_DIM              128")
    lines.append("")
    lines.append("#define ENC_FC3_IN                 128")
    lines.append("#define ENC_FC3_OUT                64")
    lines.append("")
    lines.append("/* ── Residual Block ── */")
    lines.append("#define RES_FC1_IN                 64")
    lines.append("#define RES_FC1_OUT                64")
    lines.append("#define RES_NORM1_DIM              64")
    lines.append("#define RES_FC2_IN                 64")
    lines.append("#define RES_FC2_OUT                64")
    lines.append("#define RES_NORM2_DIM              64")
    lines.append("")
    lines.append("/* ── Head ── */")
    lines.append("#define HEAD_FC1_IN                64")
    lines.append("#define HEAD_FC1_OUT               32")
    lines.append("#define HEAD_NORM_DIM              32")
    lines.append("#define HEAD_FC2_IN                32")
    lines.append("#define HEAD_FC2_OUT               1")
    lines.append("")
    lines.append("/* ── Aux resistance head ── */")
    lines.append("#define AUX_RES_IN                 64")
    lines.append("#define AUX_RES_OUT                1")
    lines.append("")
    lines.append("/* ── Activation ── */")
    lines.append("#define PINN_ACTIVATION            \"gelu\"")
    lines.append("")
    lines.append("/* ── LayerNorm epsilon ── */")
    lines.append("#define LAYERNORM_EPS              1e-5f")
    lines.append("")
    lines.append("/* ── Buffer sizing ── */")
    lines.append("#define PINN_MAX_BUF_SIZE           132")
    lines.append("")
    lines.append("#endif /* PINN_META_H */")

    path = os.path.join(out_dir, "pinn_meta.h")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote: {path}  ({len(lines)} lines)")


# ═══════════════════════════════════════════════════════════════════════
# CNN meta
# ═══════════════════════════════════════════════════════════════════════

def write_cnn_meta(out_dir):
    lines = []
    lines.append("/* Auto-generated by export_weights.py */")
    lines.append("#ifndef CNN_META_H")
    lines.append("#define CNN_META_H")
    lines.append("")
    lines.append("/* ── Input / Output ── */")
    lines.append("#define CNN_INPUT_CHANNELS          2")
    lines.append("#define CNN_INPUT_LENGTH            128")
    lines.append("#define CNN_NUM_CLASSES             3")
    lines.append("")
    lines.append("/* ── Stem: Conv1d(2→16, k7, s2, p3) ── */")
    lines.append("#define CNN_STEM_IN_CH              2")
    lines.append("#define CNN_STEM_OUT_CH             16")
    lines.append("#define CNN_STEM_KERNEL             7")
    lines.append("#define CNN_STEM_STRIDE             2")
    lines.append("#define CNN_STEM_PAD                3")
    lines.append("#define CNN_STEM_OUT_LEN            64")
    lines.append("")
    lines.append("/* ── Body Block 0: 16→16, identity skip, k7 ── */")
    lines.append("#define CNN_B0_CONV1_IN_CH          16")
    lines.append("#define CNN_B0_CONV1_OUT_CH         16")
    lines.append("#define CNN_B0_CONV1_KERNEL         7")
    lines.append("#define CNN_B0_CONV1_PAD            3")
    lines.append("#define CNN_B0_CONV2_IN_CH          16")
    lines.append("#define CNN_B0_CONV2_OUT_CH         16")
    lines.append("#define CNN_B0_CONV2_KERNEL         7")
    lines.append("#define CNN_B0_CONV2_PAD            3")
    lines.append("#define CNN_B0_CONV2_OUT_LEN        64")
    lines.append("#define CNN_B0_POOL_KERNEL          2")
    lines.append("#define CNN_B0_POOL_STRIDE          2")
    lines.append("#define CNN_B0_OUT_LEN              32")
    lines.append("")
    lines.append("/* ── Body Block 1: 16→32, 1×1 shortcut, k7 ── */")
    lines.append("#define CNN_B1_SC_IN_CH             16")
    lines.append("#define CNN_B1_SC_OUT_CH            32")
    lines.append("#define CNN_B1_CONV1_IN_CH          16")
    lines.append("#define CNN_B1_CONV1_OUT_CH         32")
    lines.append("#define CNN_B1_CONV1_KERNEL         7")
    lines.append("#define CNN_B1_CONV1_PAD            3")
    lines.append("#define CNN_B1_CONV1_OUT_LEN        32")
    lines.append("#define CNN_B1_CONV2_IN_CH          32")
    lines.append("#define CNN_B1_CONV2_OUT_CH         32")
    lines.append("#define CNN_B1_CONV2_KERNEL         7")
    lines.append("#define CNN_B1_CONV2_PAD            3")
    lines.append("#define CNN_B1_CONV2_OUT_LEN        32")
    lines.append("#define CNN_B1_POOL_KERNEL          2")
    lines.append("#define CNN_B1_POOL_STRIDE          2")
    lines.append("#define CNN_B1_OUT_LEN              16")
    lines.append("")
    lines.append("/* ── Body Block 2: 32→48, 1×1 shortcut, k5 ── */")
    lines.append("#define CNN_B2_SC_IN_CH             32")
    lines.append("#define CNN_B2_SC_OUT_CH            48")
    lines.append("#define CNN_B2_CONV1_IN_CH          32")
    lines.append("#define CNN_B2_CONV1_OUT_CH         48")
    lines.append("#define CNN_B2_CONV1_KERNEL         5")
    lines.append("#define CNN_B2_CONV1_PAD            2")
    lines.append("#define CNN_B2_CONV1_OUT_LEN        16")
    lines.append("#define CNN_B2_CONV2_IN_CH          48")
    lines.append("#define CNN_B2_CONV2_OUT_CH         48")
    lines.append("#define CNN_B2_CONV2_KERNEL         5")
    lines.append("#define CNN_B2_CONV2_PAD            2")
    lines.append("#define CNN_B2_CONV2_OUT_LEN        16")
    lines.append("#define CNN_B2_POOL_KERNEL          2")
    lines.append("#define CNN_B2_POOL_STRIDE          2")
    lines.append("#define CNN_B2_OUT_LEN              8")
    lines.append("")
    lines.append("/* ── GAP + Heads ── */")
    lines.append("#define CNN_FEATURE_DIM             48")
    lines.append("#define CNN_CLS_FC1_IN              48")
    lines.append("#define CNN_CLS_FC1_OUT             48")
    lines.append("#define CNN_CLS_FC2_IN              48")
    lines.append("#define CNN_CLS_FC2_OUT             24")
    lines.append("#define CNN_CLS_FC3_IN              24")
    lines.append("#define CNN_CLS_FC3_OUT             3")
    lines.append("#define CNN_RUL_FC1_IN              48")
    lines.append("#define CNN_RUL_FC1_OUT             48")
    lines.append("#define CNN_RUL_FC2_IN              48")
    lines.append("#define CNN_RUL_FC2_OUT             24")
    lines.append("#define CNN_RUL_FC3_IN              24")
    lines.append("#define CNN_RUL_FC3_OUT             1")
    lines.append("")
    lines.append("/* ── Buffer sizing ── */")
    max_buf = max(16*64, 32*32, 48*16, 48*8, 48, 32, 24, 3)
    lines.append(f"#define CNN_MAX_BUF_SIZE            {max_buf}")
    lines.append("")
    lines.append("#endif /* CNN_META_H */")

    path = os.path.join(out_dir, "cnn_meta.h")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote: {path}  ({len(lines)} lines)")


# ═══════════════════════════════════════════════════════════════════════
# Scaler export
# ═══════════════════════════════════════════════════════════════════════

def write_scalers(out_dir):
    lines = []
    lines.append("/* Auto-generated by export_weights.py */")
    lines.append("#ifndef SCALERS_H")
    lines.append("#define SCALERS_H")
    lines.append("")

    # PINN feature scaler
    with open(PINN_SCALER, "rb") as f:
        sc = pickle.load(f)
    mean = sc.mean_.astype(np.float32)
    std = sc.scale_.astype(np.float32)
    std = np.where(std < 1e-8, 1.0, std)

    lines.append(f"/* PINN feature scaler (mean + std, each {len(mean)}-d) */")
    for label, arr in [("PINN_SCALER_MEAN", mean), ("PINN_SCALER_STD", std)]:
        flat = arr.flatten()
        lines.append(f"static const float {label}[{len(flat)}] = {{")
        for i in range(0, len(flat), 8):
            chunk = flat[i:i+8]
            vals = ", ".join(f"{v:.8f}f" for v in chunk)
            comma = "," if i + 8 < len(flat) else ""
            lines.append(f"    {vals}{comma}")
        lines.append("};")
        lines.append("")

    # CNN IC + gradient scalers
    with open(CNN_SCALER, "rb") as f:
        scs = pickle.load(f)

    for key in ["ic_scaler", "ig_scaler"]:
        sc = scs[key]
        mean = sc.mean_.astype(np.float32)
        std = sc.scale_.astype(np.float32)
        std = np.where(std < 1e-8, 1.0, std)
        c_prefix = "CNN_IC" if key == "ic_scaler" else "CNN_IG"

        for label, arr in [(f"{c_prefix}_SCALER_MEAN", mean), (f"{c_prefix}_SCALER_STD", std)]:
            flat = arr.flatten()
            lines.append(f"/* {key}: {label} */")
            lines.append(f"static const float {label}[{len(flat)}] = {{")
            for i in range(0, len(flat), 8):
                chunk = flat[i:i+8]
                vals = ", ".join(f"{v:.8f}f" for v in chunk)
                comma = "," if i + 8 < len(flat) else ""
                lines.append(f"    {vals}{comma}")
            lines.append("};")
            lines.append("")

    lines.append("#endif /* SCALERS_H */")

    path = os.path.join(out_dir, "scalers.h")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote: {path}  ({len(lines)} lines)")


# ═══════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════

def main():
    print("=" * 60)
    print("Exporting PINN weights (FP32)...")
    print("=" * 60)
    pinn_weights = extract_weights_fp32(PINN_ONNX)
    write_weight_header(pinn_weights, "PINN_WEIGHTS_H",
                        os.path.join(OUT_DIR, "pinn_weights.h"))
    write_pinn_meta(OUT_DIR)

    print()
    print("=" * 60)
    print("Exporting CNN weights (FP32)...")
    print("=" * 60)
    cnn_weights = extract_weights_fp32(CNN_ONNX)
    write_weight_header(cnn_weights, "CNN_WEIGHTS_H",
                        os.path.join(OUT_DIR, "cnn_weights.h"))
    write_cnn_meta(OUT_DIR)

    print()
    print("=" * 60)
    print("Exporting scalers...")
    print("=" * 60)
    write_scalers(OUT_DIR)

    print()
    print("Done. Ready for C compilation.")


if __name__ == "__main__":
    main()
