/* Auto-generated by export_weights.py */
#ifndef MODEL_META_H
#define MODEL_META_H

/* ── Input / Output ── */
#define MODEL_INPUT_CHANNELS   2
#define MODEL_INPUT_LENGTH      128
#define MODEL_NUM_CLASSES       3       /* stage_logits */

/* ── Stem ── */
#define STEM_CONV_IN_CH          2
#define STEM_CONV_OUT_CH         16
#define STEM_CONV_KERNEL         7
#define STEM_CONV_STRIDE         2
#define STEM_CONV_PAD            3
#define STEM_OUT_LENGTH          64      /* (128 - 7 + 2*3)/2 + 1 = 64 */

/* ── Body Block 0 (16ch → 16ch, identity skip, then pool) ── */
#define B0_CONV1_IN_CH           16
#define B0_CONV1_OUT_CH          16
#define B0_CONV1_KERNEL          7
#define B0_CONV1_STRIDE          1
#define B0_CONV1_PAD             3
#define B0_CONV1_OUT_LEN         64      /* (64-7+6)/1+1 = 64 */

#define B0_CONV2_IN_CH           16
#define B0_CONV2_OUT_CH          16
#define B0_CONV2_KERNEL          7
#define B0_CONV2_STRIDE          1
#define B0_CONV2_PAD             3
#define B0_CONV2_OUT_LEN         64

#define B0_POOL_KERNEL           2
#define B0_POOL_STRIDE           2
#define B0_OUT_LENGTH            32      /* 64/2 = 32 */

/* ── Body Block 1 (16ch → 32ch, 1×1 shortcut, then pool) ── */
#define B1_SC_IN_CH              16
#define B1_SC_OUT_CH             32
#define B1_SC_KERNEL             1
#define B1_SC_STRIDE             1
#define B1_SC_PAD                0
#define B1_CONV1_IN_CH           16
#define B1_CONV1_OUT_CH          32
#define B1_CONV1_KERNEL          7
#define B1_CONV1_STRIDE          1
#define B1_CONV1_PAD             3
#define B1_CONV1_OUT_LEN         32
#define B1_CONV2_IN_CH           32
#define B1_CONV2_OUT_CH          32
#define B1_CONV2_KERNEL          7
#define B1_CONV2_STRIDE          1
#define B1_CONV2_PAD             3
#define B1_CONV2_OUT_LEN         32
#define B1_POOL_KERNEL           2
#define B1_POOL_STRIDE           2
#define B1_OUT_LENGTH            16      /* 32/2 = 16 */

/* ── Body Block 2 (32ch → 48ch, 1×1 shortcut, then pool) ── */
#define B2_SC_IN_CH              32
#define B2_SC_OUT_CH             48
#define B2_SC_KERNEL             1
#define B2_SC_STRIDE             1
#define B2_SC_PAD                0
#define B2_CONV1_IN_CH           32
#define B2_CONV1_OUT_CH          48
#define B2_CONV1_KERNEL          5
#define B2_CONV1_STRIDE          1
#define B2_CONV1_PAD             2
#define B2_CONV1_OUT_LEN         16
#define B2_CONV2_IN_CH           48
#define B2_CONV2_OUT_CH          48
#define B2_CONV2_KERNEL          5
#define B2_CONV2_STRIDE          1
#define B2_CONV2_PAD             2
#define B2_CONV2_OUT_LEN         16
#define B2_POOL_KERNEL           2
#define B2_POOL_STRIDE           2
#define B2_OUT_LENGTH            8       /* 16/2 = 8 */

/* ── Feature dimension (after GAP) ── */
#define FEATURE_DIM               48

/* ── Classification Head ── */
#define CLS_FC1_IN                48
#define CLS_FC1_OUT               48
#define CLS_FC2_IN                48
#define CLS_FC2_OUT               24
#define CLS_FC3_IN                24
#define CLS_FC3_OUT               3

/* ── RUL Regression Head ── */
#define RUL_FC1_IN                48
#define RUL_FC1_OUT               48
#define RUL_FC2_IN                48
#define RUL_FC2_OUT               24
#define RUL_FC3_IN                24
#define RUL_FC3_OUT               1

/* ── Buffer sizing ── */
/* Max intermediate buffer size across all layers */
#define MAX_BUF_SIZE              1024

#endif /* MODEL_META_H */